### ISSUE TITLE
java.net.bindexception cannot assign requested address (bind failed)

### ISSUE THREAD

**Issue by hfazai** [vaadin/base-starter-gradle#12]
I'm trying to run my app using 'appRun' gretty task but i'm having this error : java.net.bindexception cannot assign requested address (bind failed)

I'm using :
- gradle 6.8.3 
- Gretty : id("org.gretty") version "3.0.4"
- Vaadin Gradle Plugin: id("com.vaadin") version "20.0.1"
- vaadinVersion = "20.0.1"

Running in production mode:
````KOTLIN
vaadin {
  pnpmEnable = true
  productionMode = false
}
````

Any idea how to fix this? Thanks!

**Comment by caalador** [comment]
Doesn't that mean that there is another process using the port where the application would open?
Check the usage of port 8080 and close the application using that or change the gretty port by adding the port to the gretty block in `build.gradle`
```
gretty {
  port = 9999
}
```

**Comment by hfazai** [comment]
I tried with changing the port in gretty blockt:
```
gretty {
  contextPath = "/"
  servletContainer = "jetty9.4"
  httpPort = 9999
}
```
But still having the same issue.

**Comment by hfazai** [comment]
@caalador 
I changed to gretty 2.3.1. I get another error: `Exception in thread "Thread-164" java.lang.IllegalStateException: The configuration :grettyNoSpringBoot was resolved from a thread not managed by Gradle.`

**Comment by caalador** [comment]
The last error is due to using an incompatible gretty version.
Some places seem to indicate that downgrading to 3.0.1 might help in some cases or changing from the servletContainer from 'jetty9.4' to 'tomcat8' 

What os are you running on?
Also what else is on the stacktrace?

**Comment by hfazai** [comment]
Downgrading to 3.0.1 resolves the problem :+1: 

- My OS is Fedora 32
- This is the stacktrace when using 3.0.4
```
* Exception is:
Caused by: java.net.BindException: Cannot assign requested address (bind failed)
at org.akhikhl.gretty.ServiceProtocol.createReader(ServiceProtocol.groovy:20)
at org.akhikhl.gretty.ServiceProtocol.createReader(ServiceProtocol.groovy)
at org.akhikhl.gretty.ServiceProtocol$createReader.call(Unknown Source)
at org.akhikhl.gretty.LauncherBase.beforeLaunch(LauncherBase.groovy:57)
at org.akhikhl.gretty.DefaultLauncher.super$2$beforeLaunch(DefaultLauncher.groovy)
at org.akhikhl.gretty.DefaultLauncher.beforeLaunch(DefaultLauncher.groovy:58)
at org.akhikhl.gretty.LauncherBase.launch(LauncherBase.groovy:141)
at org.akhikhl.gretty.Launcher$launch.call(Unknown Source)
at org.akhikhl.gretty.StartBaseTask.action(StartBaseTask.groovy:87)
at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
... 119 more
```

**Comment by caalador** [comment]
It might be the same type of issue as https://github.com/gretty-gradle-plugin/gretty/issues/147

This will need some more investigation, but good that you can get forward with the project.

**Comment by hfazai** [comment]
@caalador Thanks for the help!
